In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    max_index = np.argmax(prediction[0])
    print(max_index)
    if max_index==0:
        print("Rock")
    elif max_index==1:
        print("Paper")
    elif max_index==2:
        print("Scissor")
    else:
        print("Nothing")
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

1/1 [==============================] - 1s 899ms/step
3
Nothing
[[0.10216945 0.0038646  0.18333851 0.7106274 ]]
1/1 [==============================] - 0s 45ms/step
3
Nothing
[[1.0406472e-02 6.0765255e-05 3.1663440e-03 9.8636639e-01]]
1/1 [==============================] - 0s 53ms/step
3
Nothing
[[0.05732502 0.00291025 0.02513711 0.91462755]]
1/1 [==============================] - 0s 41ms/step
3
Nothing
[[1.8211754e-02 6.3250668e-04 8.6534340e-03 9.7250223e-01]]
1/1 [==============================] - 0s 37ms/step
3
Nothing
[[1.6561992e-02 6.6087215e-04 4.9683205e-03 9.7780877e-01]]
1/1 [==============================] - 0s 32ms/step
3
Nothing
[[0.1281497  0.00707658 0.13845536 0.72631836]]
1/1 [==============================] - 0s 37ms/step
3
Nothing
[[0.02496303 0.00255105 0.03942572 0.9330602 ]]
1/1 [==============================] - 0s 54ms/step
3
Nothing
[[0.03320033 0.00189151 0.0069286  0.9579795 ]]
1/1 [==============================] - 0s 36ms/step
3
Nothing
[[0.11934198 0.002325

KeyboardInterrupt: 